ProyectoCompuCibVista/ProyectoCompuCibVista/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using ProyectoCompuCibVista.Models;
using System.Net.Http.Formatting;
using System.Text;

namespace ProyectoCompuCibVista.Controllers
{
    public class ClienteController : Controller
    {
        async Task<List<Cliente>> getClientes()
        {
            List<Cliente> temporal = new List<Cliente>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/api/Cliente/getClientes");
                HttpResponseMessage mensaje = await client.GetAsync("getClientes");
                string cadena = await mensaje.Content.ReadAsStringAsync();

                temporal = JsonConvert.DeserializeObject<List<Cliente>>(cadena).Select(
                    s => new Cliente
                    {
                        IdCliente= s.IdCliente,
                        CodigoCliente = s.CodigoCliente,
                        nombre = s.nombre,
                        apellido = s.apellido,
                        direccion = s.direccion,
                        correo = s.correo,
                        contrasenia = s.contrasenia,
                        dni = s.dni,
                    }).ToList();
            }
            return temporal;
        }

        [HttpGet]
        async Task<List<Cliente>> getCliente(int clienteId)
        {
            List<Cliente> temporal = new List<Cliente>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/api/Cliente/obtenerCliente/" + clienteId);
                HttpResponseMessage mensaje = await client.GetAsync("getClientes");
                string cadena = await mensaje.Content.ReadAsStringAsync();

                temporal = JsonConvert.DeserializeObject<List<Cliente>>(cadena).Select(
                    s => new Cliente
                    {
                        IdCliente = s.IdCliente,
                        CodigoCliente = s.CodigoCliente,
                        nombre = s.nombre,
                        apellido = s.apellido,
                        direccion = s.direccion,
                        correo = s.correo,
                        contrasenia = s.contrasenia,
                        dni = s.dni,
                    }).ToList();
            }
            return temporal;
        }

        //[HttpGet]
        //async Task<List<Producto>> getProductosxCat(int categoriaId)
        //{
        //    List<Producto> temporal = new List<Producto>();
        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://localhost:7258/");
        //        HttpResponseMessage mensaje = await client.GetAsync("api/Producto/obtenerProductoxCategoria/" + categoriaId);
        //        string cadena = await mensaje.Content.ReadAsStringAsync();

        //        temporal = JsonConvert.DeserializeObject<List<Producto>>(cadena).Select(
        //            s => new Producto
        //            {
        //                ProductoId = s.ProductoId,
        //                Nombre = s.Nombre,
        //                Precio = s.Precio,
        //                FechaCreacion = s.FechaCreacion,
        //                Foto = s.Foto,
        //                CategoriaId = s.CategoriaId,
        //                Categoria = s.Categoria,
        //                Stock = s.Stock,
        //            }).ToList();
        //    }
        //    return temporal;
        //}

        //[HttpGet]
        //async Task<List<Producto>> getProductosxNom(string nom)
        //{
        //    List<Producto> temporal = new List<Producto>();
        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://localhost:7258/");
        //        HttpResponseMessage mensaje = await client.GetAsync("api/Producto/obtenerProductoxNom/" + nom);
        //        string cadena = await mensaje.Content.ReadAsStringAsync();

        //        temporal = JsonConvert.DeserializeObject<List<Producto>>(cadena).Select(
        //            s => new Producto
        //            {
        //                ProductoId = s.ProductoId,
        //                Nombre = s.Nombre,
        //                Precio = s.Precio,
        //                FechaCreacion = s.FechaCreacion,
        //                Foto = s.Foto,
        //                CategoriaId = s.CategoriaId,
        //                Categoria = s.Categoria,
        //                Stock = s.Stock,
        //            }).ToList();
        //    }
        //    return temporal;
        //}
        //async Task<List<Categoria>> getCategorias()
        //{
        //    List<Categoria> temporal = new List<Categoria>();
        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://localhost:7258/api/Categoria/getCategorias");
        //        HttpResponseMessage mensaje = await client.GetAsync("getCategorias");
        //        string cadena = await mensaje.Content.ReadAsStringAsync();

        //        temporal = JsonConvert.DeserializeObject<List<Categoria>>(cadena).Select(
        //            s => new Categoria
        //            {
        //                CategoriaId = s.CategoriaId,
        //                Nombre = s.Nombre,
        //            }).ToList();
        //    }
        //    return temporal;
        //}
        public async Task<IActionResult> Index()
        {
            return View(await getClientes());
        }

        public async Task<IActionResult> Create()
        {
            return View(await Task.Run(() => new Cliente()));
        }
        //public async Task<IActionResult> ProductosxCat(int categoriaId = 0)
        //{
        //    ViewBag.cat = categoriaId;
        //    ViewBag.categoria = new SelectList(getCategorias().Result, "CategoriaId", "Nombre");
        //    return View(await getProductosxCat(categoriaId));
        //}

        //public async Task<IActionResult> ProductosxNom(string nom = "")
        //{

        //    return View(await getProductosxNom(nom));
        //}
        [HttpPost]
        public async Task<IActionResult> Create(Cliente reg)
        {
            string mensaje = "";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/api/Cliente/createCliente");
                StringContent contenido = new StringContent(JsonConvert.SerializeObject(reg), Encoding.UTF8, "application/json");
                HttpResponseMessage msg = await client.PostAsync("createCliente", contenido);
                mensaje = await msg.Content.ReadAsStringAsync();

            }
            if (mensaje == "1")
            {
                ViewBag.mensaje = "El Cliente se Creó Correctamente!";
                TempData["mensaje"] = "Cliente registrado correctamente";
                ViewBag.code = "1";
                return View(await Task.Run(() => reg));
            }
            else if (mensaje == "2")
            {
                ViewBag.mensaje = "El Cliente ya existe!";
                ViewBag.code = "2";
                return View(await Task.Run(() => reg));
            }
            else
            {
                ViewBag.mensaje = "Error al Crear el Cliente";
                ViewBag.code = "0";
                return View(await Task.Run(() => reg));
            }
            //ViewBag.categorias = new SelectList(await getCategorias(), "CategoriaId", "nombre", reg.CategoriaId);
            //return View(await Task.Run(() => reg));
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/");
            var request = clienteHttp.GetAsync("api/Producto/obtenerCliente/" + id).Result;

            var resultString = request.Content.ReadAsStringAsync().Result;
            var objE = JsonConvert.DeserializeObject<Cliente>(resultString);
            return View(objE);
        }
        [HttpPost]
        public ActionResult Edit(Cliente objE)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/");
            var request = clienteHttp.PutAsync("/api/Cliente/UpdateCliente", objE, new
            JsonMediaTypeFormatter()).Result;
            if (request.IsSuccessStatusCode)
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var estado = JsonConvert.DeserializeObject<int>(resultString);
                if (estado == 1)
                {
                    ViewBag.mensaje = estado + " Cliente actualizado correctamente..!!";
                    ViewBag.code = "1";
                    return View(objE);
                }
                else
                {
                    ViewBag.mensaje = "Error al actualizar el Cliente";
                    ViewBag.code = "0";
                    return View(objE);
                }
                //return View(objE);
            }
            return View();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/");
            var request = clienteHttp.GetAsync("api/Cliente/obtenerCliente/" + id).Result;
            if (request.IsSuccessStatusCode)
            {

ProyectoCompuCibVista/ProyectoCompuCibVista/Controllers/ContactoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProyectoCompuCibVista.Models;

namespace ProyectoCompuCibVista.Controllers
{
    public class ContactoController : Controller
    {
        public async Task<IActionResult> ListarContactos()
        {
            return View(await getContactos());
        }
        async Task<List<Contacto>> getContactos()
        {
            List<Contacto> temporal = new List<Contacto>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/api/Contacto/getContactos");
                HttpResponseMessage mensaje = await client.GetAsync("getContactos");
                string cadena = await mensaje.Content.ReadAsStringAsync();

                temporal = JsonConvert.DeserializeObject<List<Contacto>>(cadena).Select(
                    s => new Contacto
                    {
                        IdContacta = s.IdContacta,
                        nombreapellido = s.nombreapellido,
                        correo = s.correo,
                        asunto = s.asunto,
                        mensaje = s.mensaje,
                    }).ToList();
            }
            return temporal;
        }
        [HttpGet]
        public ActionResult eliminarContacto(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/");
            var request = clienteHttp.DeleteAsync("api/Contacto/eliminarContacto/" + id).Result;
            if (request.IsSuccessStatusCode)
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var estado = JsonConvert.DeserializeObject<bool>(resultString);
                if (estado)
                {
                    return RedirectToAction("ListarContactos");
                }
            }
            return View();
        }
    }
}

ProyectoCompuCibVista/ProyectoCompuCibVista/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProyectoCompuCibVista.Models;
using System.Net.Http.Formatting;
using System.Text;

namespace ProyectoCompuCibVista.Controllers
{
    public class VentaController : Controller
    {
        async Task<List<Venta>> getVentas()
        {
            List<Venta> temporal = new List<Venta>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/api/Venta/");
                HttpResponseMessage mensaje = await client.GetAsync("getVentas");
                string cadena = await mensaje.Content.ReadAsStringAsync();

                temporal = JsonConvert.DeserializeObject<List<Venta>>(cadena).Select(
                    s => new Venta
                    {
                        VentaId = s.VentaId,
                        name = s.name,
                        lastName = s.lastName,
                        address = s.address,
                        landmark = s.landmark,
                        district = s.district,
                        phoneNumber = s.phoneNumber,
                        paymentMethod = s.paymentMethod,
                        IdOrden = s.IdOrden,
                        DiaVenta = s.DiaVenta,
                    }).ToList();
            }
            return temporal;
        }
        public async Task<IActionResult> ListarVenta()
        {
            return View(await getVentas());
        }
        //public async Task<IActionResult> Create()
        //{
        //    return View(await Task.Run(() => new Usuario()));
        //}
        //[HttpPost]
        //public async Task<IActionResult> Create(Usuario reg)
        //{
        //    string mensaje = "";
        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://localhost:7258/api/Usuario/createUsuario");
        //        StringContent contenido = new StringContent(JsonConvert.SerializeObject(reg), Encoding.UTF8, "application/json");
        //        HttpResponseMessage msg = await client.PostAsync("createUsuario", contenido);
        //        mensaje = await msg.Content.ReadAsStringAsync();

        //    }
        //    ViewBag.mensaje = mensaje;
        //    //ViewBag.categorias = new SelectList(await getCategorias(), "CategoriaId", "nombre", reg.CategoriaId);
        //    return View(await Task.Run(() => reg));
        //}
        [HttpGet]
        public ActionResult Edit(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/");
            var request = clienteHttp.GetAsync("api/Venta/obtenerVenta/" + id).Result;

            var resultString = request.Content.ReadAsStringAsync().Result;
            var objE = JsonConvert.DeserializeObject<Venta>(resultString);
            return View(objE);
        }
        [HttpPost]
        public ActionResult Edit(Venta objE)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/");
            var request = clienteHttp.PutAsync("/api/Venta/updateVenta", objE, new
            JsonMediaTypeFormatter()).Result;
            if (request.IsSuccessStatusCode)
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var estado = JsonConvert.DeserializeObject<int>(resultString);
                if (estado == 1)
                {
                    ViewBag.mensaje = estado + " Venta actualizada correctamente..!!";
                    return View(objE);
                }
                return View(objE);
            }
            return View();
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/");
            var request = clienteHttp.GetAsync("api/Venta/obtenerVenta/" + id).Result;
            if (request.IsSuccessStatusCode)
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var objE = JsonConvert.DeserializeObject<Venta>(resultString);
                return View(objE);
            }

            return View();
        }
        [HttpGet]
        public ActionResult eliminarVenta(int id)
        {
            HttpClient clienteHttp = new HttpClient();
            clienteHttp.BaseAddress = new Uri("http://www.tienditacompucib.somee.com/");
            var request = clienteHttp.DeleteAsync("api/Venta/eliminarVenta/" + id).Result;
            if (request.IsSuccessStatusCode)
            {
                var resultString = request.Content.ReadAsStringAsync().Result;
                var estado = JsonConvert.DeserializeObject<bool>(resultString);
                if (estado)
                {
                    return RedirectToAction("ListarVenta");
                }
            }
            return View();
        }
    }
}

ProyectoCompuCibVista/ProyectoCompuCibVista/Views/Shared/PRUEBA.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
    <title>@ViewData["Title"] - ProyectoCompuCibVista</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/estiloprueba.css" asp-append-version="true" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/MiEstilo.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoCompuCibVista.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </head>
    <body>

    <!--Main Navigation-->
<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
        <div class="position-sticky">
            <div class="list-group list-group-flush mx-3 mt-4">
                    <a class="list-group-item list-group-item-action py-2 ripple" aria-current="true" class="nav-link text-light" asp-area="" asp-controller="Venta" asp-action="ListarVenta">
                        <i class="fas fa-shopping-cart fa-fw me-3"></i><span>Ventas</span>
                </a>
                    <a class="list-group-item list-group-item-action py-2 ripple" aria-current="true" asp-area="" asp-controller="Contacto" asp-action="ListarContactos">
                    <i class="fas fa-chart-area fa-fw me-3"></i><span>Contacto</span>
                </a>
                    <a class="list-group-item list-group-item-action py-2 ripple" aria-current="true" asp-area="" asp-controller="Producto" asp-action="ProductosxCat">
                    <i class="fas fa-lock fa-fw me-3"></i><span>Productos</span>
                </a>
                    <a class="list-group-item list-group-item-action py-2 ripple" aria-current="true" asp-area="" asp-controller="Cliente" asp-action="Index">
                    <i class="fas fa-chart-line fa-fw me-3"></i><span>Clientes</span>
                </a>
                    <a class="list-group-item list-group-item-action py-2 ripple" aria-current="true" asp-area="" asp-controller="Reclamo" asp-action="ReclamosxCorreo">
                    <i class="fas fa-chart-pie fa-fw me-3"></i><span>Reclamos</span>
                </a>
                    <a class="list-group-item list-group-item-action py-2 ripple" aria-current="true" asp-area="" asp-controller="Usuario" asp-action="ListarEmpleado">
                    <i class="fas fa-users fa-fw me-3"></i><span>Empleados</span>
                </a>
            </div>
        </div>
    </nav>
    <!-- Sidebar -->
    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#sidebarMenu"
                    aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Brand -->
            <a class="navbar-brand" href="#">
                    <img src="~/fotos/logo.jpg" height="25" alt="CompuCib"
                     loading="lazy" />
            </a>
            <!-- Search form -->
                <form class="d-none d-md-flex input-group w-auto my-auto" action="/Producto/ProductosxNom" method="post">
                    <input autocomplete="off" type="search" id="nom" name="nom" value="" class="form-control rounded" style="min-width: 225px;" />
                    <button class="input-group-text border-0"><i class="fas fa-search"></i></button>
                </form>
                @*<form method="get" action="/Reclamo/ListaReclamosN">*@
            <!-- Right links -->
            <ul class="navbar-nav ms-auto d-flex flex-row">
                <!-- Notification dropdown -->
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle hidden-arrow" id="navbarDropdownMenuLink"
                      role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-bell"></i>
                            <span class="badge rounded-pill badge-notification bg-danger"><span id="volume_data"></span></span>
                    </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        <li>
                            <a class="dropdown-item" href="/Reclamo/ReclamosxCorreo">Reclamos</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Nuevos Reclamos</a>
                        </li>
                    </ul>
                </li>
                @*</form>*@

                <!-- Icon dropdown --
                    class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"
                <!-- Avatar -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center" 
                       id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" class="rounded-circle"
                             height="22" alt="Avatar" loading="lazy" />
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        <li>
                            <a class="dropdown-item" href="">Mi Perfil</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Opciones</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="/Seguridad/Login">Salir</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
</header>
<!--Main Navigation-->
<!--Main layout-->
<main style="margin-top: 58px;">
    <div class="container pt-4"></div>
</main>
<!--Main layout-->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script>
        window.watsonAssistantChatOptions = {
            integrationID: "143c2b25-8599-4f2a-a129-494b9b430f1c", // The ID of this integration.
            region: "us-south", // The region your integration is hosted in.
            serviceInstanceID: "c0db494b-4942-44b7-b65d-852554e23949", // The ID of your service instance.
            onLoad: function (instance) { instance.render(); }
        };
        setTimeout(function () {
            const t = document.createElement('script');
            t.src = "https://web-chat.global.assistant.watson.appdomain.cloud/versions/" + (window.watsonAssistantChatOptions.clientVersion || 'latest') + "/WatsonAssistantChatEntry.js";
            document.head.appendChild(t);
        });
    </script>
    <script>
        function getData() {
            $.getJSON("http://www.tienditacompucib.somee.com/api/Reclamo/numeroReclamos", function (d) {
                $('#volume_data').text(d.numerosReclamos);
            });
        }
        getData(); // first call
        setInterval(getData, 3000);
        </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>


ProyectoCompuCibVista/ProyectoCompuCibVista/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoCompuCibVista</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/MiEstilo.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoCompuCibVista.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoCompuCibVista</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Usuario" asp-action="ListarEmpleado">Administración Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Venta" asp-action="ListarVenta">Administración Ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contacto" asp-action="ListarContactos">Administración Contacta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Producto" asp-action="ProductosxCat">Administración Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Cliente" asp-action="Index">Administración Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Reclamo" asp-action="ReclamosxCorreo">Administración Reclamos</a>
                        </li>
@*                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Producto" asp-action="ProductosxNom">Administración Productos Dos</a>
                        </li>*@
@*                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Contactanos</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script>
        window.watsonAssistantChatOptions = {
            integrationID: "143c2b25-8599-4f2a-a129-494b9b430f1c", // The ID of this integration.
            region: "us-south", // The region your integration is hosted in.
            serviceInstanceID: "c0db494b-4942-44b7-b65d-852554e23949", // The ID of your service instance.
            onLoad: function (instance) { instance.render(); }
        };
        setTimeout(function () {
            const t = document.createElement('script');
            t.src = "https://web-chat.global.assistant.watson.appdomain.cloud/versions/" + (window.watsonAssistantChatOptions.clientVersion || 'latest') + "/WatsonAssistantChatEntry.js";
            document.head.appendChild(t);
        });
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>